const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // docs: [
  //   { type: "doc", id: "introduction" },
  //   { type: "doc", id: "installation" },
  //   { type: "doc", id: "usage" },
  //   { type: "doc", id: "configuration" },
  //   { type: "doc", id: "cloud-integration" },
  //   { type: "doc", id: "slack-setup" },
  //   { type: "doc", id: "qr-code" },
  //   { type: "doc", id: "contributing" },
  //   { type: "doc", id: "faq" },
  //   { type: "doc", id: "license" },
  // ],
};

export default sidebars;
